version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: sekolah_db
      POSTGRES_USER: sekolah_user
      POSTGRES_PASSWORD: sekolah_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
